In [1]:
import pandas as pd

s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
student = {
    "Monika":85,
    "Amit":92,
    "Neha":78
}

s = pd.Series(student)

print(s)

Monika    85
Amit      92
Neha      78
dtype: int64

In [4]:
print(s[0])
print(s["Monika"])

85
85

/tmp/ipykernel_970/2497672687.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [5]:
print(s.index)
print(s.values)
print(s.dtype)
print(s.shape)
print(s.size)

Index(['Monika', 'Amit', 'Neha'], dtype='object')
[85 92 78]
int64
(3,)
3

In [7]:
marks = [80,90,75,95]

s = pd.Series(marks)

print(s)

0    80
1    90
2    75
3    95
dtype: int64

In [8]:
print(s.index)
print(s.values)
print(s.dtype)
print(s.shape)
print(s.size)

RangeIndex(start=0, stop=4, step=1)
[80 90 75 95]
int64
(4,)
4

In [9]:
print("Sum:", s.sum())
print("Mean:", s.mean())
print("Max:", s.max())
print("Min:", s.min())
print("Count:", s.count())
print("Median:", s.median())
print("Standard Deviation:", s.std())

Sum: 340
Mean: 85.0
Max: 95
Min: 75
Count: 4
Median: 85.0
Standard Deviation: 9.128709291752768

In [10]:
s = pd.Series([30,10,20], index=['c','a','b'])

print(s.sort_index())

a    10
b    20
c    30
dtype: int64

In [13]:
s = pd.Series([10, None, 30, None])

#print(s.isnull())
print(s.notnull())

0     True
1    False
2     True
3    False
dtype: bool

In [16]:
print(s.fillna(s.mean()))

0    10.0
1    20.0
2    30.0
3    20.0
dtype: float64

In [17]:
print(s.dropna())

0    10.0
2    30.0
dtype: float64

In [18]:
s = pd.Series(['A','B','A','C','B','A'])

print(s.value_counts())

A    3
B    2
C    1
Name: count, dtype: int64

In [19]:
data = {
    "Name":["Aman","Neha","Rahul"],
    "Age":[22,21,23],
    "Marks":[85,90,88]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0   Aman   22     85
1   Neha   21     90
2  Rahul   23     88

In [25]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.values)
print(df.dtypes)
print(df.size)

(3, 3)
Index(['Name', 'Age', 'Marks'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
[['Aman' 22 85]
 ['Neha' 21 90]
 ['Rahul' 23 88]]
Name     object
Age       int64
Marks     int64
dtype: object
9

In [28]:
import os

print(os.getcwd())      # Current working directory
print(os.listdir())     # Files in the current directory

/content
['.config', 'student.csv', 'sample_data']

In [29]:
df = pd.read_csv("student.csv")

print(df)

     StudentID     Name   Age  Gender Course  Marks        City
0          101  Charlie  19.0  Female    BCA   95.0  Chandigarh
1          102    Frank  22.0    Male   BCom   85.0     Chennai
2          103    Priya   NaN    Male  BTech   65.0        Pune
3          104      Ivy  19.0    Male   BCom   70.0     Chennai
4          105    Rahul  22.0  Female   BCom   60.0     Kolkata
..         ...      ...   ...     ...    ...    ...         ...
97         198     Nina  18.0  Female    BSc   85.0        Pune
98         199    Grace  20.0  Female    BCA   85.0   Hyderabad
99         200    Grace  18.0    Male    BCA   75.0      Jaipur
100        101  Charlie  19.0  Female    BCA   95.0  Chandigarh
101        102    Frank  22.0    Male   BCom   85.0     Chennai

[102 rows x 7 columns]

In [32]:
df.head(3)

   StudentID     Name   Age  Gender Course  Marks        City
0        101  Charlie  19.0  Female    BCA   95.0  Chandigarh
1        102    Frank  22.0    Male   BCom   85.0     Chennai
2        103    Priya   NaN    Male  BTech   65.0        Pune

In [34]:
df.tail(2)

     StudentID     Name   Age  Gender Course  Marks        City
100        101  Charlie  19.0  Female    BCA   95.0  Chandigarh
101        102    Frank  22.0    Male   BCom   85.0     Chennai

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  102 non-null    int64
 1   Name       102 non-null    object
 2   Age        81 non-null     float64
 3   Gender     102 non-null    object
 4   Course     102 non-null    object
 5   Marks      95 non-null     float64
 6   City       102 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 5.7+ KB

In [36]:
df.describe()

        StudentID        Age      Marks
count  102.000000  81.000000  95.000000
mean   149.539216  19.950617  73.789474
std     29.523165   1.482407  12.284651
min    101.000000  18.000000  55.000000
25%    124.250000  19.000000  62.500000
50%    149.500000  20.000000  75.000000
75%    174.750000  21.000000  85.000000
max    200.000000  22.000000  95.000000

In [39]:
df[["Name","Marks"]]

        Name  Marks
0    Charlie   95.0
1      Frank   85.0
2      Priya   65.0
3        Ivy   70.0
4      Rahul   60.0
..       ...    ...
97      Nina   85.0
98     Grace   85.0
99     Grace   75.0
100  Charlie   95.0
101    Frank   85.0

[102 rows x 2 columns]

In [44]:

df.iloc[0:3,0:2]

   StudentID     Name
0        101  Charlie
1        102    Frank
2        103    Priya

In [49]:
#df[df["Marks"] > 80]
df[(df["Marks"] > 80) &
   (df["Age"] > 21)]

     StudentID    Name   Age  Gender Course  Marks       City
1          102   Frank  22.0    Male   BCom   85.0    Chennai
26         127  Vikram  22.0  Female   BCom   90.0    Lucknow
37         138   Diana  22.0    Male    BCA   90.0  Hyderabad
95         196   Rahul  22.0  Female  BTech   95.0    Chennai
101        102   Frank  22.0    Male   BCom   85.0    Chennai

In [50]:
df.isnull().sum()

StudentID     0
Name          0
Age          21
Gender        0
Course        0
Marks         7
City          0
dtype: int64

In [66]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
97     False
98     False
99     False
100     True
101     True
Length: 102, dtype: bool

In [67]:
df.duplicated().sum()

np.int64(2)

In [71]:
df[df.duplicated(keep=False)]

     StudentID     Name   Age  Gender Course  Marks        City
0          101  Charlie  19.0  Female    BCA   95.0  Chandigarh
1          102    Frank  22.0    Male   BCom   85.0     Chennai
100        101  Charlie  19.0  Female    BCA   95.0  Chandigarh
101        102    Frank  22.0    Male   BCom   85.0     Chennai

In [64]:
df.dropna()
df.dropna(axis=1)
#df.fillna(0)
df["Marks"].mean()
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df["Age"] =df["Age"].fillna(df["Age"].median())

In [65]:
df.isnull().sum()

StudentID    0
Name         0
Age          0
Gender       0
Course       0
Marks        0
City         0
dtype: int64

In [46]:

df.loc[0]

StudentID           101
Name            Charlie
Age                19.0
Gender           Female
Course              BCA
Marks              95.0
City         Chandigarh
Name: 0, dtype: object

In [47]:
df.iloc[0]

StudentID           101
Name            Charlie
Age                19.0
Gender           Female
Course              BCA
Marks              95.0
City         Chandigarh
Name: 0, dtype: object